"use client";

import { useState } from "react";

export default function HomePage() {
  const DAILY_LIMIT = 3;
  const DAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

  const [form, setForm] = useState({
    qualification: "GCSE",
    subjects: "",
    examDates: "",
    weakAreas: "",
    hoursPerDay: "1",
    availableDays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    sessionLength: "20–25 minutes",
    energy: "Medium",
    studyStyle: "ADHD-friendly",
    struggles: "",
    priority: "I feel behind",
    currentSituation: "I’m behind",
    adjustmentStyle: "Make it easier",
  });

  const [plan, setPlan] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");
  const [followUpMessage, setFollowUpMessage] = useState("");
  const [checkIns, setCheckIns] = useState([]);

  function updateForm(field, value) {
    setForm((current) => ({
      ...current,
      [field]: value,
    }));
  }

  function toggleDay(day) {
    setForm((current) => {
      const alreadySelected = current.availableDays.includes(day);

      return {
        ...current,
        availableDays: alreadySelected
          ? current.availableDays.filter((item) => item !== day)
          : [...current.availableDays, day],
      };
    });
  }

  async function generatePlan() {
    setIsLoading(true);
    setErrorMessage("");
    setPlan("");
    setFollowUpMessage("");

    const today = new Date().toISOString().split("T")[0];
    const usageKey = "neuroplan_daily_usage";
    const savedUsage = JSON.parse(localStorage.getItem(usageKey) || "{}");

    if (savedUsage.date !== today) {
      savedUsage.date = today;
      savedUsage.count = 0;
    }

    if (savedUsage.count >= DAILY_LIMIT) {
      setIsLoading(false);
      setErrorMessage(
        "You have reached today’s free AI plan limit. Please come back tomorrow."
      );
      return;
    }

    try {
      const response = await fetch("/api/generate-plan", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(form),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Something went wrong.");
      }

      savedUsage.count += 1;
      localStorage.setItem(usageKey, JSON.stringify(savedUsage));

      const savedPlan = {
        createdAt: new Date().toISOString(),
        form,
        plan: data.plan,
        checkIns: [],
      };

      localStorage.setItem("neuroplan_current_plan", JSON.stringify(savedPlan));

      setPlan(data.plan);
      setCheckIns([]);
    } catch (error) {
      setErrorMessage(
        "Sorry, NeuroPlan could not generate a plan right now. Please try again in a moment."
      );
    } finally {
      setIsLoading(false);
    }
  }

  function copyPlan() {
    if (!plan) return;
    navigator.clipboard.writeText(plan);
    alert("Your plan has been copied.");
  }

  function downloadPlan() {
    if (!plan) return;

    const fileText = `NeuroPlan Study Revision Plan

Qualification: ${form.qualification}
Subjects: ${form.subjects || "Not provided"}
Exam dates/deadlines: ${form.examDates || "Not provided"}
Weak areas: ${form.weakAreas || "Not provided"}
Study days: ${form.availableDays.join(", ")}
Session length: ${form.sessionLength}
Study mode: ${form.studyStyle}
Energy level: ${form.energy}

${plan}

Generated by NeuroPlan Study
https://neuroplanstudy.com
`;

    const blob = new Blob([fileText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = "neuroplan-study-plan.txt";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  }

  function printPlan() {
    window.print();
  }

  function checkIn(status) {
    const today = new Date().toISOString().split("T")[0];

    const newCheckIn = {
      date: today,
      status,
    };

    const updatedCheckIns = [...checkIns, newCheckIn];
    setCheckIns(updatedCheckIns);

    const savedPlan = JSON.parse(
      localStorage.getItem("neuroplan_current_plan") || "{}"
    );

    localStorage.setItem(
      "neuroplan_current_plan",
      JSON.stringify({
        ...savedPlan,
        checkIns: updatedCheckIns,
      })
    );

    if (status === "completed") {
      setFollowUpMessage(
        "Good work — today counts. Tomorrow, keep the same plan but avoid adding extra pressure. Consistency matters more than doing everything perfectly."
      );
    }

    if (status === "some") {
      setFollowUpMessage(
        "That still counts. Tomorrow, reduce the first task slightly and start with the subject or topic that feels most urgent. Do not restart the whole plan."
      );
    }

    if (status === "missed") {
      setFollowUpMessage(
        "No reset needed. Tomorrow, ignore anything non-urgent and do one small recovery session first. Pick the weakest or closest-deadline task and do 10–20 minutes."
      );
    }

    if (status === "easier") {
      setFollowUpMessage(
        "Switch to low-energy mode tomorrow: one short session, one tiny task, and no guilt. The aim is to keep the habit alive, not to force a full revision day."
      );
    }
  }

  function renderPlan() {
    if (!plan) return null;

    return plan.split("\n").map((line, index) => {
      const cleanLine = line.trim();

      if (!cleanLine) {
        return <br key={index} />;
      }

      if (cleanLine.startsWith("# ")) {
        return (
          <h3 key={index} className="planMainHeading">
            {cleanLine.replace("# ", "")}
          </h3>
        );
      }

      if (cleanLine.startsWith("## ")) {
        return (
          <h4 key={index} className="planSectionHeading">
            {cleanLine.replace("## ", "")}
          </h4>
        );
      }

      if (cleanLine.startsWith("- ")) {
        return (
          <p key={index} className="planBullet">
            • {cleanLine.replace("- ", "")}
          </p>
        );
      }

      return (
        <p key={index} className="planParagraph">
          {cleanLine}
        </p>
      );
    });
  }

  return (
    <main className="page">
      <section className="hero">
        <p className="tagline">NeuroPlan Study</p>

        <h1>Revision planning that adapts when life happens.</h1>

        <p className="subtitle">
          Build a calm, realistic revision plan for GCSEs, A-Levels, BTECs and
          university work. Check in with your plan, track progress and adjust
          when you fall behind.
        </p>

        <div className="buttons">
          <a href="#planner" className="primaryButton">
            Create my free AI plan
          </a>
          <a href="#how-it-works" className="secondaryButton">
            See how it works
          </a>
        </div>

        <p className="heroNote">
          Free AI version · Built in the UK · No account needed
        </p>
      </section>

      <section className="section introSection" id="how-it-works">
        <div>
          <p className="sectionLabel">Why NeuroPlan exists</p>
          <h2>Most revision plans break the first time you miss a day.</h2>
        </div>

        <p>
          NeuroPlan is built for real students, not perfect routines. It helps
          you start small, focus on what matters, check in honestly, and adjust
          without restarting from zero.
        </p>

        <div className="cards">
          <div className="card">
            <h3>Adaptive planning</h3>
            <p>
              Your plan includes catch-up space and follow-up options for days
              that do not go perfectly.
            </p>
          </div>

          <div className="card">
            <h3>Low-friction check-ins</h3>
            <p>
              Tell NeuroPlan whether you completed, partly completed or missed
              the day.
            </p>
          </div>

          <div className="card">
            <h3>Overwhelm-aware structure</h3>
            <p>
              Short sessions, realistic study days and small first tasks make
              revision easier to start.
            </p>
          </div>
        </div>
      </section>

      <section className="section whoSection">
        <p className="sectionLabel">Who it is for</p>
        <h2>Built for UK students who need revision to feel doable.</h2>

        <div className="pillGrid">
          <span>GCSE students</span>
          <span>A-Level students</span>
          <span>BTEC and T-Level learners</span>
          <span>University students</span>
          <span>ADHD learners</span>
          <span>Autistic students</span>
          <span>Anxious students</span>
          <span>Burnt-out students</span>
        </div>
      </section>

      <section className="planner" id="planner">
        <p className="sectionLabel">Free AI planner</p>
        <h2>Create your revision plan</h2>

        <p>
          Answer a few high-value questions. NeuroPlan will create a plan based
          on your subjects, deadlines, weak areas, available days and energy.
        </p>

        <p
          style={{
            marginTop: "10px",
            fontWeight: "700",
            color: "#5b4b2f",
          }}
        >
          Free early version: 3 AI plans per day per device.
        </p>

        <div className="plannerForm">
          <label>
            Qualification
            <select
              value={form.qualification}
              onChange={(e) => updateForm("qualification", e.target.value)}
            >
              <option>GCSE</option>
              <option>A-Level</option>
              <option>BTEC</option>
              <option>T-Level</option>
              <option>University</option>
              <option>Access course</option>
              <option>Other</option>
            </select>
          </label>

          <label>
            Current situation
            <select
              value={form.currentSituation}
              onChange={(e) => updateForm("currentSituation", e.target.value)}
            >
              <option>I’m starting from scratch</option>
              <option>I’ve done some revision</option>
              <option>I’m behind</option>
              <option>My exam/deadline is soon</option>
              <option>I need a reset plan</option>
              <option>I need to stay consistent</option>
            </select>
          </label>

          <label>
            Main priority
            <select
              value={form.priority}
              onChange={(e) => updateForm("priority", e.target.value)}
            >
              <option>I feel behind</option>
              <option>I need help starting</option>
              <option>I need a weekly plan</option>
              <option>I have exams soon</option>
              <option>I feel burnt out</option>
              <option>I need structure</option>
            </select>
          </label>

          <label>
            Preferred session length
            <select
              value={form.sessionLength}
              onChange={(e) => updateForm("sessionLength", e.target.value)}
            >
              <option>10–15 minutes</option>
              <option>20–25 minutes</option>
              <option>30–45 minutes</option>
              <option>60 minutes</option>
            </select>
          </label>

          <label>
            Subjects
            <textarea
              placeholder="Example: Maths, English Literature, Biology"
              value={form.subjects}
              onChange={(e) => updateForm("subjects", e.target.value)}
            />
          </label>

          <label>
            Exam dates or deadlines
            <textarea
              placeholder="Example: Maths paper 1 - 16 May, Biology - 23 May"
              value={form.examDates}
              onChange={(e) => updateForm("examDates", e.target.value)}
            />
          </label>

          <label>
            Weak areas or hardest topics
            <textarea
              placeholder="Example: algebra, poetry quotes, biology required practicals, essay structure..."
              value={form.weakAreas}
              onChange={(e) => updateForm("weakAreas", e.target.value)}
            />
          </label>

          <label>
            What are you struggling with?
            <textarea
              placeholder="Example: I avoid starting, I panic when I see everything, I keep falling behind..."
              value={form.struggles}
              onChange={(e) => updateForm("struggles", e.target.value)}
            />
          </label>

          <label>
            Hours available per study day
            <select
              value={form.hoursPerDay}
              onChange={(e) => updateForm("hoursPerDay", e.target.value)}
            >
              <option value="1">Around 1 hour</option>
              <option value="2">Around 2 hours</option>
              <option value="3">3+ hours</option>
            </select>
          </label>

          <label>
            Energy level right now
            <select
              value={form.energy}
              onChange={(e) => updateForm("energy", e.target.value)}
            >
              <option>Low</option>
              <option>Medium</option>
              <option>High</option>
            </select>
          </label>

          <label>
            Study mode
            <select
              value={form.studyStyle}
              onChange={(e) => updateForm("studyStyle", e.target.value)}
            >
              <option>ADHD-friendly</option>
              <option>Autism-friendly</option>
              <option>Burnout / low-energy</option>
              <option>Last-minute panic mode</option>
              <option>Flexible plan</option>
            </select>
          </label>

          <label>
            If I fall behind, NeuroPlan should
            <select
              value={form.adjustmentStyle}
              onChange={(e) => updateForm("adjustmentStyle", e.target.value)}
            >
              <option>Make it easier</option>
              <option>Keep me on track</option>
              <option>Prioritise urgent tasks</option>
              <option>Give me a low-energy version</option>
            </select>
          </label>

          <div
            style={{
              gridColumn: "span 2",
              background: "rgba(255, 255, 255, 0.7)",
              border: "2px solid rgba(124, 58, 237, 0.12)",
              borderRadius: "20px",
              padding: "18px",
            }}
          >
            <p
              style={{
                marginTop: 0,
                fontWeight: 900,
                color: "#374151",
              }}
            >
              Which days can you realistically study?
            </p>

            <div
              style={{
                display: "flex",
                flexWrap: "wrap",
                gap: "10px",
              }}
            >
              {DAYS.map((day) => (
                <button
                  key={day}
                  type="button"
                  onClick={() => toggleDay(day)}
                  style={{
                    padding: "10px 14px",
                    borderRadius: "999px",
                    border: "none",
                    fontWeight: 900,
                    cursor: "pointer",
                    color: form.availableDays.includes(day)
                      ? "white"
                      : "#374151",
                    background: form.availableDays.includes(day)
                      ? "linear-gradient(135deg, #7c3aed, #2563eb)"
                      : "white",
                  }}
                >
                  {day}
                </button>
              ))}
            </div>
          </div>

          <button type="button" onClick={generatePlan} disabled={isLoading}>
            {isLoading ? "Creating your plan..." : "Generate my adaptive plan"}
          </button>
        </div>

        {errorMessage && <p className="errorMessage">{errorMessage}</p>}

        {plan && (
          <div className="resultBox">
            <div className="resultHeader">
              <div>
                <p className="sectionLabel">Your result</p>
                <h3>Your NeuroPlan</h3>
              </div>

              <div className="resultActions">
                <button type="button" onClick={copyPlan}>
                  Copy
                </button>
                <button type="button" onClick={downloadPlan}>
                  Download
                </button>
                <button type="button" onClick={printPlan}>
                  Print / PDF
                </button>
              </div>
            </div>

            <div className="planMeta">
              <span>{form.qualification}</span>
              <span>{form.studyStyle}</span>
              <span>{form.energy} energy</span>
              <span>{form.sessionLength}</span>
            </div>

            <div className="planContent">{renderPlan()}</div>

            <div
              style={{
                marginTop: "22px",
                background: "white",
                color: "#111827",
                borderRadius: "22px",
                padding: "22px",
              }}
            >
              <p className="sectionLabel">Today’s check-in</p>
              <h3>How did today go?</h3>

              <p>
                NeuroPlan saves this check-in on this device and gives you a
                simple next-step adjustment.
              </p>

              <div
                style={{
                  display: "flex",
                  flexWrap: "wrap",
                  gap: "10px",
                  marginTop: "14px",
                }}
              >
                <button type="button" onClick={() => checkIn("completed")}>
                  I completed today
                </button>
                <button type="button" onClick={() => checkIn("some")}>
                  I did some
                </button>
                <button type="button" onClick={() => checkIn("missed")}>
                  I missed it
                </button>
                <button type="button" onClick={() => checkIn("easier")}>
                  I need an easier day
                </button>
              </div>

              {followUpMessage && (
                <p
                  style={{
                    marginTop: "18px",
                    background: "#f5f3ff",
                    color: "#4c1d95",
                    padding: "16px",
                    borderRadius: "16px",
                    fontWeight: 800,
                  }}
                >
                  {followUpMessage}
                </p>
              )}

              {checkIns.length > 0 && (
                <p
                  style={{
                    marginTop: "12px",
                    color: "#4b5563",
                    fontWeight: 700,
                  }}
                >
                  Check-ins saved on this device: {checkIns.length}
                </p>
              )}
            </div>
          </div>
        )}
      </section>

      <section className="section waitlistSection">
        <p className="sectionLabel">Early updates</p>
        <h2>Want to follow NeuroPlan as it grows?</h2>

        <p>
          Join the early updates list to hear when NeuroPlan adds saved plans,
          printable timetables, accounts, reminders and premium features.
        </p>

        <a
          className="primaryButton"
          href="mailto:help@neuroplanstudy.com?subject=Join%20NeuroPlan%20updates&body=Hi%2C%20please%20add%20me%20to%20the%20NeuroPlan%20Study%20early%20updates%20list."
        >
          Join the early updates list
        </a>

        <p
          style={{
            marginTop: "14px",
            fontSize: "0.95rem",
            color: "#6b5d42",
          }}
        >
          This opens your email app. You can ask to be removed from updates at
          any time.
        </p>
      </section>

      <section className="section trustSection">
        <p className="sectionLabel">Important note</p>
        <h2>A study tool, not pressure.</h2>
        <p>
          NeuroPlan is here to help you structure revision into smaller steps.
          It does not guarantee grades and it is not medical or mental health
          advice. If studying is seriously affecting your wellbeing, speak to a
          trusted adult, teacher, GP, college, university or support service.
        </p>
      </section>

      <footer>
        <p>© 2026 NeuroPlan Study. Built in the UK.</p>

        <div className="footerLinks">
          <a href="/about">About</a>
          <a href="/privacy">Privacy Policy</a>
          <a href="/terms">Terms of Use</a>
        </div>
      </footer>
    </main>
  );
}
